version: '3.4'

services:
  php:
    image: biyongyao/php-fpm-alpine-dev:8.3
    container_name: hatch-php_php83
    restart: on-failure
    working_dir: /var/www/html/hatch-php
    user: "${UID-1000}:${GID-1000}"
    volumes:
      - "../hatch-php:/var/www/html/hatch-php"
    networks:
      hatch-php-network:
        ipv4_address: 192.168.220.20

networks:
  hatch-php-network:
    ipam:
      config:
        - subnet: 192.168.220.0/24